config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("privacy-policy", TemplateView.as_view(template_name="pages/privacy.html"), name="privacy"),
    path("terms-of-use", TemplateView.as_view(template_name="pages/terms.html"), name="terms"),

    path("", include("website_builder.websites.urls", namespace="websites")),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("website_builder.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("templates/", include("website_builder.builder.urls", namespace="builder")),
    path("contacts/", include("website_builder.contacts.urls", namespace="contacts")),
    path("subscriptions/", include("website_builder.subscriptions.urls", namespace="subscriptions")),
    path('i18n/', include('django.conf.urls.i18n')),

    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

website_builder/builder/urls.py
from django.urls import path

from website_builder.builder.views import (
    TemplateList,
    TemplateDetail,
    builder_view,
    template_preview,
    template_preview_extra_pages,
    download_template
)
from website_builder.builder.api import (
    GetTemplate,
    GetUserUploadedAssets
)

app_name = "builder"

urlpatterns = [
    path("", view=TemplateList.as_view(), name="template-list"),
    path("<slug:slug>", view=TemplateDetail.as_view(), name="template-detail"),
    path("preview/<slug:slug>", view=template_preview, name="template-preview"),
    path("preview/<slug:slug>/<str:page_slug>", view=template_preview_extra_pages, name="template-preview-extra"),

    path("builder/<uuid:id>", view=builder_view, name="builder"),
    path("builder/<int:id>", view=builder_view, name="builder"),
    path("download/<int:id>", view=download_template, name="download"),
    #api urls
    path("api/v1/template/<uuid:id>",view=GetTemplate.as_view(),name="get-template-api"),
    path("api/v1/template/<int:id>",view=GetTemplate.as_view(),name="get-template-api"),
    path("api/v1/user-assets",view=GetUserUploadedAssets.as_view(),name="get-user-assets"),

]

website_builder/contacts/urls.py
from django.urls import path

from website_builder.contacts.views import (
    create_contact,
    builder_contact_form
)

app_name = "contacts"

urlpatterns = [
    path("<uuid:uuid>",view=builder_contact_form,name="builder-form"),
    path("new", view=create_contact, name="create-contact"),
]

website_builder/subscriptions/urls.py
from django.urls import path

from website_builder.subscriptions.views import (
    pricing_page,
    create_checkout_session,
    ProcessWebhookView,
    customer_portal
)

app_name = "subs"

urlpatterns = [
    path("", view=pricing_page, name="pricing-page"),
    path("create-checkout-session", view=create_checkout_session, name="create-checkout-session"),
    path("webhooks", view=ProcessWebhookView.as_view(), name="stripe-webhooks"),
    path('customer-portal',view=customer_portal,name="customer-portal")
]

website_builder/users/urls.py
from django.urls import path

from website_builder.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

website_builder/websites/urls.py
from django.urls import path

from website_builder.websites.views import (
    save_website,
    UserWebsiteList,
    user_website_detail,
    UpladAssets,
    delete_website,
    download_website,
    visit_website,
    redirect_short_website
)

from website_builder.websites.aws_views import (
    host_website_on_s3,
    request_certificate,
    domain_instructions,
    validate_domain,
    check_if_domain_validated,
    host_website_instruction,
)

app_name = "websites"

urlpatterns = [
    path('<uuid:uuid>',view=visit_website,name="visit-website"),
    path("my-websites", view=UserWebsiteList.as_view(), name="website-list"),
    #path('<str:short_id>',view=redirect_short_website,name="visit-website-short"),
    path("my-websites/<uuid:uid>", view=user_website_detail, name="website-detail"),

    path("save-website/",view=save_website,name="save-website"),
    path("upload/assets", view=UpladAssets.as_view(), name="upload-assets"),
    path("delete/<uuid:uid>", view=delete_website, name="delete-website"),
    path("download/<uuid:uid>", view=download_website, name="download-website"),

    path("my-websites/domain/<uuid:uuid>",
        view=domain_instructions, name="website-domain"),
    path('host-website-on-s3/<uuid:uuid>',view=host_website_on_s3,name="host-website"),
    path('request_certificate/<uuid:uuid>',view=request_certificate,name="amc"),
    path('validate_domain/<uuid:uuid>',view=validate_domain,name="validate_domain"),
    path('check_if_domain_validated/<uuid:uuid>',
        view=check_if_domain_validated,
        name="check_validation_status"),
    path('host-website-instruction/<uuid:uuid>',
        view=host_website_instruction,
        name="host-instruction"),

]

website_builder/builder/forms.py
from django.forms import ModelForm

from website_builder.builder.widgets import HtmlEditor
from website_builder.builder.models import (
    Template,
    Block
)
class TemplateAdminForm(ModelForm):
    model = Template
    class Meta:
        fields = '__all__'
        widgets = {
            'html_content': HtmlEditor(attrs={'style': 'width: 90%; height: 100%;'}),
        }

class BlockAdminForm(ModelForm):
    model = Block
    class Meta:
        fields = '__all__'
        widgets = {
            'html_content': HtmlEditor(attrs={'style': 'width: 90%; height: 100%;'}),
        }

website_builder/contacts/forms.py
from django.forms import ModelForm
from website_builder.contacts.models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        exclude = ['user']

website_builder/builder/views.py
import json
from uuid import UUID
from ratelimit.decorators import ratelimit

from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpRequest, HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView,ListView
from django.views.decorators.cache import cache_page

from django.db.models import Q
from django.contrib import messages
from django.utils import timezone

from website_builder.builder.models import (
    Template,
    Block,
    TemplateCategory,
    Style,
    TemplateExtraPage
)
from website_builder.websites.models import Website,UploadedAsset
from website_builder.builder.utils import is_valid_uuid
from website_builder.websites.utils import (
    get_rendered_html_from_template
)


class TemplateList(ListView):
    paginate_by = 6
    queryset = Template.objects.filter(is_public=True)
    context_object_name = 'template_list'
    template_name = "builder/template_list.html"

    current_category = 0
    current_css = 0

    filters = Q(is_public=True)

    def check_if_empty(self,param):
        if param == '':
            return True
        return False

    def check_if_digit(self,param):
        if not self.check_if_empty(param):
            if param.isdigit():
               return True
        return False

    def get_queryset(self):
        category = self.request.GET.get('category','')
        css = self.request.GET.get('css','')

        if self.check_if_digit(category):
            self.filters &= Q(category=category)
            self.current_category = int(category)

        if self.check_if_digit(css):
            self.filters &= Q(styles=css)
            self.current_css = int(css)

        try:
            templates = Template.objects.filter(self.filters)
        except:
            templates = Template.objects.filter(is_public=True)

        return templates

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        categories = TemplateCategory.objects.all()
        styles = Style.objects.filter(style__exact='')


        current_dict = {
            'category': {
                'name':_("Categories"),
                'obj': categories,
                'current_id':self.current_category,
                'extra_params':{
                    'css': self.current_css,
                }
            },
            'css': {
                'name':"CSS",
                'obj': styles,
                'current_id':self.current_css,
                'extra_params':{
                    'category': self.current_category,
                }
            }
        }

        context['current_dict'] = current_dict

        return context

class TemplateDetail(DetailView):
    queryset = Template.objects.all()
    context_object_name = 'template'
    template_name = "builder/template_detail.html"
    slug_url_kwarg = 'slug'


@login_required
def builder_view(request: HttpRequest,id) -> HttpResponse:
    user = request.user
    website = None
    max_page = 5

    if is_valid_uuid(id):
        website = get_object_or_404(Website,uid=id,user=user)
        template = website.template
    else:
        template = get_object_or_404(Template,id=id,is_editable=True)

        if user.has_subscription() and user.get_subscription_end_date() > timezone.now():
            user_sub = user.get_subscription()
            if user.websites.all().count() >= user_sub.plan.enabled_websites:
                messages.info(request,_("You have reached the maximum websites you can have in this plan!"))
                return redirect("subs:pricing-page")
        else:
            if user.websites.all().count() >= 1:
                messages.info(request,_("Only active subscribers can have more than 1 websites!"))
                return redirect("subs:pricing-page")
            if template.is_premium:
                messages.info(request,_("Only subscribers can use premium templates!"))
                return redirect("subs:pricing-page")

    if user.has_subscription():
        max_page = user.get_subscription().plan.max_page_per_site

    ctx = {
        "template":template,
        "max_page":max_page
    }
    if website:
        ctx["website"] = website

    return render(request,"builder/template_builder.html",ctx)

@cache_page(60*60*24)
def template_preview(request:HttpRequest,slug:str)-> HttpResponse:
    template = get_object_or_404(Template,slug=slug)
    ctx = {
        "template":template
    }
    return render(request,"builder/template_preview.html",ctx)

@cache_page(60*60*24)
def template_preview_extra_pages(request:HttpRequest,slug:str,page_slug:str)-> HttpResponse:
    template = get_object_or_404(Template,slug=slug)
    page = get_object_or_404(TemplateExtraPage,template=template,page_id=page_slug)
    ctx = {
        "template":template,
        "page":page
    }
    return render(request,"builder/template_preview.html",ctx)

@ratelimit(key='ip', rate='1/h')
@login_required
def download_template(request:HttpRequest,id:str)-> HttpResponseRedirect:
    was_limited = getattr(request, 'limited', False)

    if was_limited:
        messages.info(request,_("Download limit is: 1 template / hour"))
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    template = get_object_or_404(Template,id=id)
    html  = get_rendered_html_from_template(request,template)
    user = request.user
    sub = user.get_subscription()

    if not sub or not sub.plan.can_download or not sub.end_date > timezone.now():
        messages.info(request,_("You cannot download with this plan"))
        return redirect("subs:pricing-page")

    response = HttpResponse(html, content_type='application/html')
    response['Content-Disposition'] = f'attachment; filename={template.name}.html'
    return response
    
   

website_builder/contacts/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest, HttpResponse,HttpResponseRedirect
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings

from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives,send_mail
from django.utils.html import strip_tags

from website_builder.contacts.forms import ContactForm
from website_builder.contacts.models import Contact
from website_builder.websites.models import Website
from website_builder.subscriptions.emails import sendEmail

def create_contact(request:HttpRequest)-> HttpResponse:
    user = request.user
    if user.is_authenticated:
        form = ContactForm(initial={"email":user.email})
    else:
        form = ContactForm()

    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            print("hello")
            if user.is_authenticated:
                contact = form.save()
                contact.user = user
                contact.save()
            else:
                form.save()

            messages.success(request,_("Email send successfully!"))
            return redirect("home")
        else:
            messages.error(request,_("Something went wrong! Try again..."))
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    ctx = {
        "form":form
    }

    return render(request,"contacts/create_contact.html",ctx)


@csrf_exempt
def builder_contact_form(request,uuid):
    host = request.META['HTTP_HOST']
    redirect_url = host
    print("------------hello")
    print("------------hello")
    if 'HTTP_REFERER' in request.META:
        referrer = request.META['HTTP_REFERER']
        redirect_url = referrer

    print("------------meta")
    print(host)
    print(request.headers)
    print(settings.DEFAULT_EMAIL_SENDER)
    print(redirect_url)
    print("------------meta")
    if not host == settings.SITE_DEFAULT_URL or not host == "ngye.in":
        return HttpResponseRedirect(redirect_url)

    if request.method == "POST":
        try:
            website = Website.objects.get(private_uuid=uuid)
            inputs = request.POST.items()
            inputs_dict = {}
            email_list = []
            email_list.append(website.user.email)

            for k,v in inputs:
                inputs_dict[k] = str(v)
                print(k,v)
            print(inputs_dict)
            emailmessage = render_to_string('contacts/emails/builder_forms.html', {"inputs":inputs_dict,"website":website.name})
            text_content = strip_tags(emailmessage)

            msg = EmailMultiAlternatives(
                'New Email',
                text_content,
                settings.DEFAULT_EMAIL_SENDER,
                email_list
                )
            msg.attach_alternative(emailmessage, "text/html")
            msg.send()

        except:
            return HttpResponseRedirect(redirect_url)

    else:
        return HttpResponseRedirect(redirect_url)
    return HttpResponseRedirect(redirect_url)

website_builder/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

website_builder/templates/base.html
{% load static i18n compress%}<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% trans "Home" %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Free,premium tailwind bootstrap website builder!">
    <meta name="author" content="p3t3rk3">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    <link rel="preconnect" href="https://fonts.cdnfonts.com">
    <link href="https://fonts.cdnfonts.com/css/sofia-pro" rel="stylesheet">
  
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicons/site.webmanifest' %}">

    {% block css %}


    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endcompress %}
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}

      <!-- Vendor dependencies bundled as one file-->
      {% compress js %}
      <script defer src="{% static 'js/vendors.js' %}"></script>
      {% endcompress %}


      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script defer src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
     <script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "d710986f15544b91bf11dad6ed5eaccf"}'></script>
  </head>

  <body class="bg-light d-flex flex-column h-100">

    <div class="mb-md-2 mb-1">
      <nav class="navbar navbar-expand-md navbar-light w-100 bg-light">
        <button style="border:none;" class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            <span class="text-primary font-weight-light">ingyen<span class="font-italic text-dark">oldal</span></span>
          </a>

          <div class="collapse navbar-collapse  w-100 float-right" id="navbarSupportedContent">
            <ul class="navbar-nav w-100 d-flex justify-content-end ">

              <div class="btn-group dropleft">
                <button type="button" class="btn btn-transparent dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {% trans 'More' %}
                </button>
                <div class="dropdown-menu border-dark">
                  <a class="nav-link text-dark" href="{% url 'subs:pricing-page' %}">{% trans "Plans" %}</a>
<!--                   <a class="nav-link text-dark" href="{% url 'subs:pricing-page' %}">{% trans "Tutorials" %}</a>
 -->                  <a class="nav-link text-dark" href="{% url 'contacts:create-contact' %}">{% trans "Contact" %}</a>

                </div>
              </div>

              <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'builder:template-list' %}">{% trans "Templates" %}</a>
              </li>
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'websites:website-list'  %}">{% trans "My websites" %}</a>
              </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link text-dark" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="sign-up-link" class="nav-link text-dark" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="log-in-link" class="btn btn-dark" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>

        </div>

      </nav>

    </div>

    <div class="{% block container %}container{% endblock container %} flex-shrink-0 mb-md-5 mb-3">

      {% if messages %}
          {% for message in messages %}
              <div class="border border-dark alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->
    <footer class="footer mt-auto  bg-white border-top border-dark ">
      <div class="container py-3 d-flex justify-content-between">
        <ul style="font-size: 14px;">
          <li>           
              <a href="{% url 'privacy' %}">{% trans "Privacy policy" %}</a>
          </li>
          <li>
            <a href="{% url 'terms' %}">{% trans "Terms" %}</a>
          </li>
          <li>
            <a href="{% url 'contacts:create-contact' %}">{% trans "Contact" %}</a>
          </li>
          {% if user.is_staff %}
          <li>
            <a href="{% url 'admin:index' %}">{% trans "Admin" %}</a>
          </li>
          {% endif %}
        </ul>

      </div>
      <div class="bg-dark text-white p-1 d-flex justify-content-between">
        <span class="ml-3">{% trans "website by" %}
          <span class="badge badge-light">
            <a href="https://toth-peter.hu">
              p3t3r
            </a>
          </span>
        </span>
        <div>
          <form action="{% url 'set_language' %}" class="text-white mr-2" method="post">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}" />
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
                <button type="submit" name="language" value="{{ language.code }}"
                  class="btn mr-1 p-0 text-white">
                  {{ language.code }}
                </button>{% if forloop.last %}{% else %}|{% endif %}
              {% endfor %}
          </form>
        </div>
      </div>
    </footer>
    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {# Script tags with only code, no src (defer by default) #}
    {% endblock inline_javascript %}
  </body>
</html>