config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("privacy-policy", TemplateView.as_view(template_name="pages/privacy.html"), name="privacy"),
    path("terms-of-use", TemplateView.as_view(template_name="pages/terms.html"), name="terms"),

    path("", include("website_builder.websites.urls", namespace="websites")),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("website_builder.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("templates/", include("website_builder.builder.urls", namespace="builder")),
    path("contacts/", include("website_builder.contacts.urls", namespace="contacts")),
    path("subscriptions/", include("website_builder.subscriptions.urls", namespace="subscriptions")),
    path('i18n/', include('django.conf.urls.i18n')),

    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

website_builder/builder/urls.py
from django.urls import path

from website_builder.builder.views import (
    TemplateList,
    TemplateDetail,
    builder_view,
    template_preview,
    template_preview_extra_pages,
    download_template
)
from website_builder.builder.api import (
    GetTemplate,
    GetUserUploadedAssets
)

app_name = "builder"

urlpatterns = [
    path("", view=TemplateList.as_view(), name="template-list"),
    path("<slug:slug>", view=TemplateDetail.as_view(), name="template-detail"),
    path("preview/<slug:slug>", view=template_preview, name="template-preview"),
    path("preview/<slug:slug>/<str:page_slug>", view=template_preview_extra_pages, name="template-preview-extra"),

    path("builder/<uuid:id>", view=builder_view, name="builder"),
    path("builder/<int:id>", view=builder_view, name="builder"),
    path("download/<int:id>", view=download_template, name="download"),
    #api urls
    path("api/v1/template/<uuid:id>",view=GetTemplate.as_view(),name="get-template-api"),
    path("api/v1/template/<int:id>",view=GetTemplate.as_view(),name="get-template-api"),
    path("api/v1/user-assets",view=GetUserUploadedAssets.as_view(),name="get-user-assets"),

]

website_builder/contacts/urls.py
from django.urls import path

from website_builder.contacts.views import (
    create_contact,
    builder_contact_form
)

app_name = "contacts"

urlpatterns = [
    path("<uuid:uuid>",view=builder_contact_form,name="builder-form"),
    path("new", view=create_contact, name="create-contact"),
]

website_builder/users/urls.py
from django.urls import path

from website_builder.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

website_builder/websites/urls.py
from django.urls import path

from website_builder.websites.views import (
    save_website,
    UserWebsiteList,
    user_website_detail,
    UpladAssets,
    delete_website,
    download_website,
    visit_website,
    redirect_short_website
)

from website_builder.websites.aws_views import (
    host_website_on_s3,
    request_certificate,
    domain_instructions,
    validate_domain,
    check_if_domain_validated,
    host_website_instruction,
)

app_name = "websites"

urlpatterns = [
    path('<uuid:uuid>',view=visit_website,name="visit-website"),
    path("my-websites", view=UserWebsiteList.as_view(), name="website-list"),
    #path('<str:short_id>',view=redirect_short_website,name="visit-website-short"),
    path("my-websites/<uuid:uid>", view=user_website_detail, name="website-detail"),

    path("save-website/",view=save_website,name="save-website"),
    path("upload/assets", view=UpladAssets.as_view(), name="upload-assets"),
    path("delete/<uuid:uid>", view=delete_website, name="delete-website"),
    path("download/<uuid:uid>", view=download_website, name="download-website"),

    path("my-websites/domain/<uuid:uuid>",
        view=domain_instructions, name="website-domain"),
    path('host-website-on-s3/<uuid:uuid>',view=host_website_on_s3,name="host-website"),
    path('request_certificate/<uuid:uuid>',view=request_certificate,name="amc"),
    path('validate_domain/<uuid:uuid>',view=validate_domain,name="validate_domain"),
    path('check_if_domain_validated/<uuid:uuid>',
        view=check_if_domain_validated,
        name="check_validation_status"),
    path('host-website-instruction/<uuid:uuid>',
        view=host_website_instruction,
        name="host-instruction"),

]

website_builder/builder/forms.py
from django.forms import ModelForm

from website_builder.builder.widgets import HtmlEditor
from website_builder.builder.models import (
    Template,
    Block
)
class TemplateAdminForm(ModelForm):
    model = Template
    class Meta:
        fields = '__all__'
        widgets = {
            'html_content': HtmlEditor(attrs={'style': 'width: 90%; height: 100%;'}),
        }

class BlockAdminForm(ModelForm):
    model = Block
    class Meta:
        fields = '__all__'
        widgets = {
            'html_content': HtmlEditor(attrs={'style': 'width: 90%; height: 100%;'}),
        }

website_builder/contacts/forms.py
from django.forms import ModelForm
from website_builder.contacts.models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        exclude = ['user']

website_builder/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

website_builder/builder/views.py
import json
from uuid import UUID
from ratelimit.decorators import ratelimit

from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpRequest, HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView,ListView
from django.views.decorators.cache import cache_page

from django.db.models import Q
from django.contrib import messages
from django.utils import timezone

from website_builder.builder.models import (
    Template,
    Block,
    TemplateCategory,
    Style,
    TemplateExtraPage
)
from website_builder.websites.models import Website,UploadedAsset
from website_builder.builder.utils import is_valid_uuid
from website_builder.websites.utils import (
    get_rendered_html_from_template
)


class TemplateList(ListView):
    paginate_by = 6
    queryset = Template.objects.filter(is_public=True)
    context_object_name = 'template_list'
    template_name = "builder/template_list.html"

    current_category = 0
    current_css = 0

    filters = Q(is_public=True)

    def check_if_empty(self,param):
        if param == '':
            return True
        return False

    def check_if_digit(self,param):
        if not self.check_if_empty(param):
            if param.isdigit():
               return True
        return False

    def get_queryset(self):
        category = self.request.GET.get('category','')
        css = self.request.GET.get('css','')

        if self.check_if_digit(category):
            self.filters &= Q(category=category)
            self.current_category = int(category)

        if self.check_if_digit(css):
            self.filters &= Q(styles=css)
            self.current_css = int(css)

        try:
            templates = Template.objects.filter(self.filters)
        except:
            templates = Template.objects.filter(is_public=True)

        return templates

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        categories = TemplateCategory.objects.all()
        styles = Style.objects.filter(style__exact='')


        current_dict = {
            'category': {
                'name':_("Categories"),
                'obj': categories,
                'current_id':self.current_category,
                'extra_params':{
                    'css': self.current_css,
                }
            },
            'css': {
                'name':"CSS",
                'obj': styles,
                'current_id':self.current_css,
                'extra_params':{
                    'category': self.current_category,
                }
            }
        }

        context['current_dict'] = current_dict

        return context

class TemplateDetail(DetailView):
    queryset = Template.objects.all()
    context_object_name = 'template'
    template_name = "builder/template_detail.html"
    slug_url_kwarg = 'slug'


@login_required
def builder_view(request: HttpRequest,id) -> HttpResponse:
    user = request.user
    website = None
    max_page = 5

    if is_valid_uuid(id):
        website = get_object_or_404(Website,uid=id,user=user)
        template = website.template
    else:
        template = get_object_or_404(Template,id=id,is_editable=True)

        if user.has_subscription() and user.get_subscription_end_date() > timezone.now():
            user_sub = user.get_subscription()
            if user.websites.all().count() >= user_sub.plan.enabled_websites:
                messages.info(request,_("You have reached the maximum websites you can have in this plan!"))
                return redirect("subs:pricing-page")
        else:
            if user.websites.all().count() >= 1:
                messages.info(request,_("Only active subscribers can have more than 1 websites!"))
                return redirect("subs:pricing-page")
            if template.is_premium:
                messages.info(request,_("Only subscribers can use premium templates!"))
                return redirect("subs:pricing-page")

    if user.has_subscription():
        max_page = user.get_subscription().plan.max_page_per_site

    ctx = {
        "template":template,
        "max_page":max_page
    }
    if website:
        ctx["website"] = website

    return render(request,"builder/template_builder.html",ctx)

@cache_page(60*60*24)
def template_preview(request:HttpRequest,slug:str)-> HttpResponse:
    template = get_object_or_404(Template,slug=slug)
    ctx = {
        "template":template
    }
    return render(request,"builder/template_preview.html",ctx)

@cache_page(60*60*24)
def template_preview_extra_pages(request:HttpRequest,slug:str,page_slug:str)-> HttpResponse:
    template = get_object_or_404(Template,slug=slug)
    page = get_object_or_404(TemplateExtraPage,template=template,page_id=page_slug)
    ctx = {
        "template":template,
        "page":page
    }
    return render(request,"builder/template_preview.html",ctx)

@ratelimit(key='ip', rate='1/h')
@login_required
def download_template(request:HttpRequest,id:str)-> HttpResponseRedirect:
    was_limited = getattr(request, 'limited', False)

    if was_limited:
        messages.info(request,_("Download limit is: 1 template / hour"))
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    template = get_object_or_404(Template,id=id)
    html  = get_rendered_html_from_template(request,template)
    user = request.user
    sub = user.get_subscription()

    if not sub or not sub.plan.can_download or not sub.end_date > timezone.now():
        messages.info(request,_("You cannot download with this plan"))
        return redirect("subs:pricing-page")

    response = HttpResponse(html, content_type='application/html')
    response['Content-Disposition'] = f'attachment; filename={template.name}.html'
    return response
    
   

website_builder/contacts/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest, HttpResponse,HttpResponseRedirect
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings

from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives,send_mail
from django.utils.html import strip_tags

from website_builder.contacts.forms import ContactForm
from website_builder.contacts.models import Contact
from website_builder.websites.models import Website
from website_builder.subscriptions.emails import sendEmail

def create_contact(request:HttpRequest)-> HttpResponse:
    user = request.user
    if user.is_authenticated:
        form = ContactForm(initial={"email":user.email})
    else:
        form = ContactForm()

    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            print("hello")
            if user.is_authenticated:
                contact = form.save()
                contact.user = user
                contact.save()
            else:
                form.save()

            messages.success(request,_("Email send successfully!"))
            return redirect("home")
        else:
            messages.error(request,_("Something went wrong! Try again..."))
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    ctx = {
        "form":form
    }

    return render(request,"contacts/create_contact.html",ctx)


@csrf_exempt
def builder_contact_form(request,uuid):
    host = request.META['HTTP_HOST']
    redirect_url = host
    print("------------hello")
    print("------------hello")
    if 'HTTP_REFERER' in request.META:
        referrer = request.META['HTTP_REFERER']
        redirect_url = referrer

    print("------------meta")
    print(host)
    print(request.headers)
    print(settings.DEFAULT_EMAIL_SENDER)
    print(redirect_url)
    print("------------meta")
    if not host == settings.SITE_DEFAULT_URL or not host == "ngye.in":
        return HttpResponseRedirect(redirect_url)

    if request.method == "POST":
        try:
            website = Website.objects.get(private_uuid=uuid)
            inputs = request.POST.items()
            inputs_dict = {}
            email_list = []
            email_list.append(website.user.email)

            for k,v in inputs:
                inputs_dict[k] = str(v)
                print(k,v)
            print(inputs_dict)
            emailmessage = render_to_string('contacts/emails/builder_forms.html', {"inputs":inputs_dict,"website":website.name})
            text_content = strip_tags(emailmessage)

            msg = EmailMultiAlternatives(
                'New Email',
                text_content,
                settings.DEFAULT_EMAIL_SENDER,
                email_list
                )
            msg.attach_alternative(emailmessage, "text/html")
            msg.send()

        except:
            return HttpResponseRedirect(redirect_url)

    else:
        return HttpResponseRedirect(redirect_url)
    return HttpResponseRedirect(redirect_url)

website_builder/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

website_builder/templates/websites/host_instruction.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}{% trans 'Hosting instruction' %}{% endblock %}

{% block content %}
<div class="row mt-3">
 <div class="col-12">
   <div class="card border-dark">
     <div class="card-header text-center  py-5 bg-primary text-white">
      <h2>{% trans 'How to connect your domain to your site' %}</h2>
      <p>{{website.domain_name}}</p>
      <p>{{hosted_website.s3_url}}</p>
      <p>{{hosted_website.cloudfront_url}}</p>

     </div>
     <div class="card-body">
       {% if hosted_website.cloudfront_url %}
      {% include "websites/includes/edit_cname_ul.html" %}
      <p>{% trans "That's it! (The redirect proccess could take up to 48 hours)" %}</p>

       {% else %}
       <div class="text-center my-5">
         <h5>{% trans "First you have to host your website" %}</h5>
        <a class="btn btn-success btn-lg" href="{% url 'websites:host-website' uuid=website.private_uuid %}">{% trans 'Click here to host it' %}</a>
       </div>
       {% endif %}


      <hr>
      <div class="my-4 text-center">
        <p>{% trans "If you have any problem, please contact us!" %}</p>
        <a class="btn btn-outline-primary" href="{% url 'contacts:create-contact' %}">{% trans "Contact" %}</a>
      </div>
     </div>
   </div>
 </div>
</div>
{% endblock content %}

website_builder/templates/websites/index.html
<!DOCTYPE html>
<html lang="hu" style="height:100%;">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="{{website.description}}">
  <meta name="author" content="{{website.user.username}}.">
  {% if website.icon %}
  <link rel="icon" type="image/png" href="{{website.icon_small.url}}" />
  {% endif %}

  {% for s in styles %}
  {% if s.url_path %}
  <link rel="stylesheet" href="{{s.url_path}}">
  {% endif %}
  {% endfor %}

  {% for s in scripts %}
  {% if s.is_defered and s.url_path %}
  <script defer src="{{s.url_path}}"></script>
  {% endif %}
  {% endfor %}
  
  <title>{{website.name}} {% if page %} | {{page.name}}{% endif %}</title>
</head>
<body style="overflow-x: hidden;height:100%">
  <style>
    {% if website.css %}

      {% if page %}
        {{page.css|safe}}
      {% else %}
        {{website.css|safe}}
      {% endif %}

    {% else %}
      {% for s in styles %}
      {% if s.style %}
        {{s.style|safe}}
      {% endif %}
      {% endfor %}
    {% endif %}
  </style>
  
  {% if page %}
    {{page.html_content|safe}}
    {% else %}
    {{html|safe}}
    {% endif %}

  {% if show_footer %}
  <div style="width:100vw;padding:3px;"><small> Made with ❤ by: <a href="https://ingyenoldal.hu">ingyenoldal.<span style="font-style: italic;">hu</span></a></small></div>
  {% endif %}

    {% for s in scripts %}
      {% if not s.is_defered and s.url_path %}
      <script src="{{s.url_path}}"></script>
      {% endif %}
      {% if s.script %}
      <script>{{s.script|safe}}</script>
      {% endif %}
    {% endfor %}
</body>
</html>

website_builder/templates/websites/request_certificate.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Add your domain name' %}{% endblock %}

{% block content %}
<div class="row mt-3">
 <div class="col-12">
   <div class="card border-dark">
     <div class="card-header text-center  py-5 bg-primary text-white">
      <h2>{% trans 'Add your domain' %}</h2>
     </div>
     <div class="card-body">
       <div class="row">
        <div class="col-12">
          <p class="text-danger" >{% trans "Make sure you actually own this domain!" %}</p>
        </div>
        <div class="col-12 my-3">
          <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-primary" >{% trans "Continue" %}</button>
          </form>
         </div>
       </div>
      <hr>
      <div class="my-4 text-center">
        <p>{% trans "If you have any problem, please contact us!" %}</p>
        <a class="btn btn-outline-primary" href="{% url 'contacts:create-contact' %}">{% trans "Contact" %}</a>
      </div>
     </div>
   </div>
 </div>
</div>
{% endblock content %}

website_builder/templates/websites/user_website_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}{% trans 'My websites' %}{% endblock %}
{% block container %}container-fluid{% endblock container %}

{% block content %}
<div class="row mt-3 px-xl-5">
  {% if website_list %}
  <div class="col-md-6 col-lg-5 col-xl-3 mb-3 ">
    <div class="h-100">
      <a href="{% url 'builder:template-list' %}" style="text-decoration: none"class="text-dark w-100 border border-dark d-flex flex-column justify-content-center bg-white align-items-center h-100">
          <span style="font-size: 80px;">+</span>
      </a>
    </div>
  </div>
  {% for w in website_list %}
  <div class="col-md-6 col-lg-5 col-xl-3">
    <a href="{{w.get_absolute_url}}" class="w-100">
      {% if  w.image %}
        <img src="{{w.image_thumbnail.url}}" alt="{{w.name}}" class="w-100 img-fluid border border-dark shadow-sm">
      {% else %}
        <img src="{{w.template.image_thumbnail.url}}" alt="{{w.name}}" class="w-100 img-fluid border border-dark shadow-sm">
      {% endif %}
    </a>
    <p>{{w.name}}</p>
  </div>
  {% endfor %}
  {% else %}
  <div class="text-center col-12">
    <h5>{% trans "You don't have any websites yet..." %}</h5>
    <a href="{% url 'builder:template-list' %}" class="btn btn-primary mt-2">{% trans "Create" %}</a>
  </div>
  {% endif %}
</div>
<div class="row px-xl-5 d-flex justify-content-end">
  {% if is_paginated %}
  {% include "common/pagination_normal.html"  %}
{% endif %}
</div>
{% endblock content %}

website_builder/templates/websites/validate_domain.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Validate your url' %}{% endblock %}

{% block content %}
<div class="row mt-3">
 <div class="col-12">
   <div class="card border-dark">
     <div class="card-header text-center  py-5 bg-primary text-white">
      <h2>{% trans 'Validate your domain' %}</h2>
     </div>
     <div class="card-body">
       <div class="col my-3">
         <h5 class="m-4">{% trans "Your domain name:" %}
           <span class="ml-2  font-weight-light p-1 ">{{website.domain_name}}
            <button type="button" class="btn btn-outline-success btn-sm" data-toggle="modal" data-target="#editDomainModal">
              {% trans "Edit domain" %}
            </button>
            </span>
          </h5>
         <table class="table border border-dark">
          <thead class="thead-dark">
            <tr>
              <th scope="col">{% trans "Name" %}</th>
              <th scope="col">{% trans "Type" %}</th>
              <th scope="col">{% trans "Value" %}</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{hosted.validation_host}}</td>
              <td>CNAME</td>
              <td>{{hosted.validation_value}}</td>
            </tr>
          </tbody>
        </table>


        <div class="text-center mb-5 mt-2">
          <a class="btn btn-info btn-lg" href="{% url 'websites:check_validation_status' uuid=website.private_uuid %}">
            {% trans "Check if domain has been validated" %}
          </a>
        </div>
        <hr>
        <div class="text-center mb-3">
          <h3>{% trans "How to validate?" %}</h3>
        </div>
        {% include "websites/includes/edit_cname_ul.html" %}

       </div>

      <hr>
      <div class="my-4 text-center">
        <p>{% trans "If you have any problem, please contact us!" %}</p>
        <a class="btn btn-outline-primary" href="{% url 'contacts:create-contact' %}">{% trans "Contact" %}</a>
      </div>
     </div>
   </div>
 </div>
</div>
{% endblock content %}

{% block modal %}
<div class="modal fade" id="editDomainModal" tabindex="-1" aria-labelledby="editDomainModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <form action="{% url 'websites:amc' uuid=website.private_uuid %}" method="POST">
        {% csrf_token %}
      <div class="modal-header">
        <h5 class="modal-title" id="editDomainModalLabel">{% trans "Edit domain name" %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="text-danger">{% trans "Make sure you actually own this domain!" %}</p>
        {{edit_domain_form|crispy}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Close" %}</button>
        <button type="submit" class="btn btn-primary">{% trans "Edit" %}</button>
      </div>
    </div>
  </form>
  </div>
</div>
{% endblock modal %}